create or replace FUNCTION TTEC_GET_PTO_ELIG_INFO
(P_ASSIGNMENT_ID                  IN  NUMBER
,P_EFFECTIVE_DATE                 IN  DATE
,P_STATE                          OUT     VARCHAR2
,P_CITY                           OUT     VARCHAR2
,P_GRE                            OUT     VARCHAR2
) RETURN VARCHAR2 IS


 /************************************************************************************
        Program Name: TTEC_GET_PTO_ELIG_INFO 

        Description:   

        Developed by : 
        Date         :  

       Modification Log
       Name                  Version #    Date            Description
       -----                 --------     -----           -------------
    RXNETHI(ARGANO)            1.0      19-May-2023      R12.2 Upgrade Remediation
    ****************************************************************************************/



--

L_WORK_AT_HOME  VARCHAR2(1);
--
CURSOR CSR_LOCATION_ADDRESS IS
SELECT LOC.REGION_2, LOC.TOWN_OR_CITY
  /*
  START R12.2 Upgrade Remediation
  code commented by RXNETHI-ARGANO,19/05/23
  FROM HR.HR_LOCATIONS_ALL LOC,
       HR.PER_ALL_ASSIGNMENTS_F PAAF
  */
  --code added by RXNETHI-ARGANO,19/05/23
  FROM APPS.HR_LOCATIONS_ALL LOC,
       APPS.PER_ALL_ASSIGNMENTS_F PAAF
  --END R12.2 Upgrade Remediation
 WHERE LOC.LOCATION_ID = PAAF.LOCATION_ID
   AND P_EFFECTIVE_DATE BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
   AND PAAF.ASSIGNMENT_ID = P_ASSIGNMENT_ID;

CURSOR CSR_HOME_ADDRESS IS
SELECT PA.REGION_2, PA.TOWN_OR_CITY
  /*
  START R12.2 Upgrade Remediation
  code commented by RXNETHI-ARGANO,19/05/23
  FROM HR.PER_ADDRESSES PA,
       HR.PER_ALL_ASSIGNMENTS_F PAAF
  */
  --code added by RXNETHI-ARGANO,19/05/23
  FROM APPS.PER_ADDRESSES PA,
       APPS.PER_ALL_ASSIGNMENTS_F PAAF
  --END R12.2 Upgrade Remediation
  WHERE PAAF.PERSON_ID = PA.PERSON_ID
    AND PA.PRIMARY_FLAG = 'Y'
    AND DATE_TO IS NULL
    AND P_EFFECTIVE_DATE BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
    AND PAAF.ASSIGNMENT_ID = P_ASSIGNMENT_ID;
--
BEGIN

SELECT NVL(WORK_AT_HOME, 'N')
  INTO L_WORK_AT_HOME
  --FROM HR.PER_ALL_ASSIGNMENTS_F PAAF   --code commented by RXNETHI-ARGANO,19/05/23
  FROM APPS.PER_ALL_ASSIGNMENTS_F PAAF   --code added by RXNETHI-ARGANO,19/05/23
 WHERE PAAF.ASSIGNMENT_ID = P_ASSIGNMENT_ID
   AND P_EFFECTIVE_DATE BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE;

IF L_WORK_AT_HOME = 'Y' THEN
   OPEN CSR_HOME_ADDRESS ;
   FETCH CSR_HOME_ADDRESS INTO P_STATE, P_CITY;
   CLOSE CSR_HOME_ADDRESS ;
ELSE
   OPEN CSR_LOCATION_ADDRESS ;
   FETCH CSR_LOCATION_ADDRESS INTO P_STATE, P_CITY;
   CLOSE CSR_LOCATION_ADDRESS ;
END IF;

SELECT ORG.NAME
  INTO P_GRE
  --FROM HR.HR_SOFT_CODING_KEYFLEX SOFTFLEX, HR.HR_ALL_ORGANIZATION_UNITS ORG, HR.PER_ALL_ASSIGNMENTS_F PAAF         --code commented by RXNETHI-ARGANO,19/05/23
  FROM APPS.HR_SOFT_CODING_KEYFLEX SOFTFLEX, APPS.HR_ALL_ORGANIZATION_UNITS ORG, APPS.PER_ALL_ASSIGNMENTS_F PAAF     --code added by RXNETHI-ARGANO,19/05/23
 WHERE ORG.ORGANIZATION_ID = SOFTFLEX.SEGMENT1
   AND SOFTFLEX.SOFT_CODING_KEYFLEX_ID = PAAF.SOFT_CODING_KEYFLEX_ID
   AND P_EFFECTIVE_DATE BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
   AND PAAF.ASSIGNMENT_ID = P_ASSIGNMENT_ID;

RETURN L_WORK_AT_HOME;

END TTEC_GET_PTO_ELIG_INFO;
/
show errors;
/